# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-24 04:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InitialMigrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=500)),
                ('notify', models.BooleanField()),
                ('minpay', models.FloatField(validators=[django.core.validators.MinValueValidator(0.99)])),
                ('maxpay', models.FloatField(validators=[django.core.validators.MinValueValidator(0.99)])),
                ('paytype', models.CharField(choices=[(b'hourly', b'Hourly'), (b'monthly', b'Monthly')], default=b'hourly', max_length=2)),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='InitialMigrations.CityState')),
            ],
            options={
                'db_table': 'jobseeker',
            },
        ),
    ]
