# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InitialMigrations', '0001_initial'),
        ('UserRegister', '0002_jobseeker_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notify', models.BooleanField()),
                ('contactname', models.CharField(max_length=200)),
                ('employee_strength', models.IntegerField()),
                ('industry_type', models.CharField(max_length=200)),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InitialMigrations.CityState')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business',
            },
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='locations',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='locations',
            field=models.ManyToManyField(to='InitialMigrations.CityState'),
        ),
    ]
