# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobPosting', '0002_jobpost_datafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to=b'')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'postimage',
            },
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='datafile',
        ),
        migrations.AddField(
            model_name='jobpostimages',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_id', to='JobPosting.JobPost'),
        ),
    ]
