# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobPosting', '0003_auto_20200429_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostimages',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='JobPosting.JobPost'),
        ),
    ]
