# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-30 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPosting', '0007_jobbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobbid',
            name='jbseeker_id',
        ),
        migrations.DeleteModel(
            name='JobBid',
        ),
    ]
