# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-30 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobPosting', '0008_auto_20200430_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='awarded_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awarded_jobseeker_id', to='UserRegister.JobSeeker'),
        ),
    ]
