# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-30 05:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegister', '0008_auto_20200428_1042'),
        ('JobPosting', '0009_auto_20200430_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=250)),
                ('details', models.CharField(max_length=1000)),
                ('pay', models.FloatField(default=0.99, validators=[django.core.validators.MinValueValidator(0.99)])),
                ('paytype', models.CharField(choices=[(b'hourly', b'Hourly'), (b'monthly', b'Monthly')], default=b'hourly', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('jobseeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseekeruser_id', to='UserRegister.JobSeeker')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_id', to='JobPosting.JobPost')),
            ],
            options={
                'db_table': 'jobbid',
            },
        ),
    ]
