# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-21 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InitialMigrations', '0002_skill'),
        ('JobPosting', '0010_jobbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.ManyToManyField(to='InitialMigrations.Skill'),
        ),
    ]
