# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-24 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('population', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('pop_class', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'citystate',
            },
        ),
    ]
