# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-21 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InitialMigrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'skill',
            },
        ),
    ]
